### ISSUE TITLE
Leçon 21

### ISSUE THREAD

**Issue by jblezoray** [Oktogazh/Eienn#4]
Je crois que j'ai eu un bug sur la leçon 21. 
Peux-tu y jeter un oeil STP ?

[Voir copie écran ici. ](https://tinyurl.com/4vnfzh2w)

**Comment by Oktogazh** [comment]
https://en.wikipedia.org/wiki/Rickrolling
Les enregistrements modulo 7 sont toujours en accéléré, mais peut-être vais-je finir par arrêter de Rickroller les gens, parce que t'es pas le premier à considérer ça comme un bug...
Pour les enregistrements en accéléré, n'essaie pas de tout comprendre, ils sont là pour te préparer à des conversations réelles, l'objectif est de t’entraîner à reconnaître juste quelques mots dans le tas, malgré une prononciation déformée.

**Comment by jblezoray** [comment]
C'hoant am boa veñjañ din deus ar rick roll e-barzh ar gentel 21 :-)

N'em eus ket problemoù gant ar gentellioù buanaat.  N'eo ket aes o gomprenañ, met mont a ra mat memes tra.

Trugarez evit Eienn. Mat tre eo.
